services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  catalogdb:
    image: postgres
    # build:
    #   dockerfile: Services/Catalog/Catalog.API/Dockerfile
volumes:
  postgres_catalog:

